openapi: 3.0.0
info:
  title: Horos API
  description: API dla aplikacji Horos do generowania horoskopów
  version: 1.0.0

servers:
  - url: http://localhost:3000
    description: Serwer deweloperski
  - url: https://api.horos.app
    description: Serwer produkcyjny

paths:
  /api/horoscope:
    post:
      summary: Generuje nowy horoskop
      description: Generuje spersonalizowany horoskop na podstawie danych urodzeniowych
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - date
                - time
                - latitude
                - longitude
              properties:
                date:
                  type: string
                  format: date
                  example: "1990-01-01"
                time:
                  type: string
                  format: time
                  example: "12:00"
                latitude:
                  type: number
                  format: float
                  example: 52.2297
                longitude:
                  type: number
                  format: float
                  example: 21.0122
      responses:
        '200':
          description: Pomyślnie wygenerowano horoskop
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HoroscopeResponse'
        '400':
          description: Nieprawidłowe dane wejściowe
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Błąd serwera
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /api/cached-horoscope/{id}:
    get:
      summary: Pobiera zapisany horoskop
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: Identyfikator zapisanego horoskopu
      responses:
        '200':
          description: Pomyślnie pobrano horoskop
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HoroscopeResponse'
        '404':
          description: Nie znaleziono horoskopu
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /api/payment/create:
    post:
      summary: Tworzy nową sesję płatności
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - amount
                - currency
                - paymentMethod
              properties:
                amount:
                  type: number
                  example: 49.99
                currency:
                  type: string
                  example: "PLN"
                paymentMethod:
                  type: string
                  enum: [tpay, bitpay]
      responses:
        '200':
          description: Pomyślnie utworzono sesję płatności
          content:
            application/json:
              schema:
                type: object
                properties:
                  sessionId:
                    type: string
                  redirectUrl:
                    type: string

components:
  schemas:
    PlanetPosition:
      type: object
      properties:
        sign:
          type: string
          example: "Aries"
        degree:
          type: number
          example: 15.5
        house:
          type: number
          example: 1

    HoroscopeResponse:
      type: object
      properties:
        interpretation:
          type: string
          description: Wygenerowana interpretacja horoskopu
        chart:
          type: object
          description: Dane wykresu urodzeniowego
          properties:
            ascendant:
              type: number
              example: 123.45
            houses:
              type: array
              items:
                type: number
        planets:
          type: object
          additionalProperties:
            $ref: '#/components/schemas/PlanetPosition'

    Error:
      type: object
      properties:
        code:
          type: string
          example: "INVALID_INPUT"
        message:
          type: string
          example: "Nieprawidłowy format daty"

security:
  - ApiKeyAuth: []

components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: X-API-Key
